---
# tasks file for helloworld
#
- name: Copying the application file
  copy:
    src: helloworld.js
    dest: /home/ec2-user/
    owner: ec2-user
    group: ec2-user
    mode: 0644
  notify:
    - restart helloworld

- name: copy unit file
  copy:
    src: helloworld.service
    dest: /etc/systemd/system/helloworld.service
    mode: 0644
    owner: root
    group: root
  notify:
    - reload systemctl 

- name: Starting the HelloWorld node service
  service:
    name: helloworld.service
    state: started
    enabled: yes
