---
# tasks file for nodejs
- name: install nodejs and npm 
  shell: >
    curl https://raw.githubusercontent.com/creationix/nvm/v0.7.0/install.sh | sh
    creates=/home/ec2-user/.nvm/nvm.sh

- name: Install node and set version
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm install --lts && nvm install 16"
    creates=/home/ec2-user/.nvm/alias
